<?php
$pages = array();
$pages['casa_batllo'] = array(
	'title' => 'Casa Batlló',
	'img' => '1',
	'content' => '<p>La Casa Batlló trata de una remodelación integral de un edificio previamente existente en el solar, obra de Emilio Sala Cortés. Está situado en el número 43 del Paseo de Gracia de Barcelona, la ancha avenida que atraviesa el distrito del Ensanche (Eixample), en la llamada Manzana de la discordia, porque alberga además de este edificio otras obras de arquitectos modernistas: la casa Amatller, que colinda con la de Gaudí, obra de Josep Puig i Cadafalch; la Casa Lleó Morera, obra de Lluís Domènech i Montaner; la Casa Mulleras, de Enric Sagnier i Villavecchia; y la Casa Josefina Bonet, de Marcel·lià Coquillat. La construcción se realizó entre los años 1904 y 1906.</p>
		<p>La Casa Batlló es un reflejo de la plenitud artística de Gaudí: pertenece a su etapa naturalista (primera década del siglo XX), periodo en que el arquitecto perfecciona su estilo personal, inspirándose en las formas orgánicas de la naturaleza, para lo que puso en práctica toda una serie de nuevas soluciones estructurales originadas en los profundos análisis efectuados por Gaudí de la geometría reglada. A ello añade el artista catalán una gran libertad creativa y una imaginativa creación ornamental: partiendo de cierto barroquismo sus obras adquieren gran riqueza estructural, de formas y volúmenes desprovistos de rigidez racionalista o de cualquier premisa clásica.</p>
		<p>La fachada se hizo con piedra arenisca de Montjuïc, tallada según superficies regladas en forma alabeada. Las columnas tienen forma ósea, con representaciones vegetales. La carpintería es igualmente de superficies curvas, y las ventanas son de vidrios de colores de formas circulares. Gaudí conservó la forma rectangular de los balcones del edificio anterior, añadiendo unas barandillas de hierro con forma de antifaz, y dando al resto de la fachada una forma ondulada en sentido ascendente. Asimismo revistió la fachada con cerámica de pedazos de cristal de varios colores (su famoso trencadís), que Gaudí obtenía en los desechos de la vidriería Pelegrí, y cuya colocación dirigió personalmente desde el Paseo de Gracia. Para su diseño el arquitecto realizó diversas maquetas en yeso, que modeló con sus propias manos hasta conseguir la forma que buscaba, que recuerda el oleaje del Mar Mediterráneo o bien las sinuosas formas de la montaña de Montserrat.</p>
		<p>Del conjunto de la fachada destaca la tribuna del piso principal —el de la familia Batlló—, que se extiende por los laterales hasta el primer piso, alcanzando 10 metros de altura. Presenta cinco vanos cubiertos con vidrieras policromas, y sostenidos por ocho columnas de forma ósea. Para su construcción Gaudí demolió toda la parte baja de la fachada, sosteniendo el resto con unos puntales de madera, en tan precario equilibrio que el constructor, Josep Bayó, temía que se caería, durante los cuatro días que duró la operación. El friso de la tribuna está rematado con motivos escultóricos de forma vegetal, aunque en el conjunto de la forma que adquiere la tribuna algunos estudiosos creen ver la forma de un murciélago.</p>
		<p>Otro elemento característico de la fachada es su revestimiento con vidrios y cerámica de vivos colores, que crean diversos efectos visuales según la luz que incide en ellos. Para su confección, picó el anterior muro y lo recubrió de mortero de cal, sobre el que colocó los vidrios del taller Pelegrí, combinados en diferentes tonalidades; sobre estos vidrios esparció a todo lo largo de la fachada una serie de discos de cerámica (un total de 330) fabricados de forma manual en Mallorca, realizados en arcilla con diversos colores de óxidos naturales, y confeccionados en cuatro tamaños: 15, 21, 27 y 35 cm.</p>
		<p>Otra de las singularidades de la fachada son sus balcones, realizados con hierro fundido y pintados de carbonato de plomo para evitar su oxidación, circunstancia que les otorga un color marfileño. Están colocados sobre peanas de piedra con forma de concha marina. Hay un total de nueve balcones, además de las cuatro terrazas situadas sobre la tribuna. Su forma evoca un antifaz o una máscara teatral —aunque hay quien ve en ellos la parte superior de una calavera—, excepto el balcón del desván, que tiene forma de flor o de bulbo vegetal, semejante al de un tulipán o una alcachofa. Asimismo, el perfil quebrado y enroscado de estos balcones recuerda la forma de un pergamino. Casi todos tienen el mismo tamaño, excepto el del desván y el de la parte superior izquierda, que es una barandilla doble, con tres huecos. En 1983 los balcones fueron restaurados y recuperaron su color original, que se había oscurecido.</p>
		<p>Culmina la fachada una bóveda formada por arcos catenarios cubiertos con dos capas de ladrillo, recubierta con cerámica vidriada en forma de escamas —realizada en los Talleres Sebastià Ribó—, en tonos rojo, verde y azul, que recuerda el lomo de un dragón. En la parte izquierda hay una torre cilíndrica de forma bulbosa —semejante a una cabeza de ajo—, decorada con los anagramas de Jesús (IHS), María (M con la corona ducal) y José (JHP), y rematada con la típica cruz gaudiniana de cuatro brazos, orientada a los puntos cardinales. Una de las interpretaciones simbólicas que se ha dado a esta fachada es la de San Jorge luchando con el dragón, cuyas víctimas se hallan en la fachada representadas por las columnas en forma de hueso y los balcones en forma de calavera. Así, la cruz de cuatro brazos sería la espada clavada en el espinazo del animal, del que brotaría la sangre, presente en la cerámica roja de esta parte de la cubierta.</p>
		<p>El edificio presenta una fachada posterior que da al patio interior de la manzana, de igual forma ondulante y recubierta de trencadís de cerámica. El piso principal tiene un patio que sobresale del cuerpo del edificio, al que se accede por el comedor de la vivienda que fue de los señores Batlló. El resto de pisos tienen terrazas que dan a esta parte posterior del edificio, cubiertas con barandillas de reja metálica. La parte más destacada es la del desván, realizada con cerámica de vivos colores, con motivos florales y geométricos.</p>
		<p><strong>&copy; Image:</strong> <a href="https://www.flickr.com/photos/darrellg/4190254544" rel="nofollow">Casa Batllo at night detail</a> <cite>by Darrell Godliman</cite></p>'
);

$pages['sagrada_familia'] = array(
	'title' => 'Sagrada Familia',
	'img' => '2',
	'content' => '<p>Iniciada en 1882, todavía está en construcción. Es la obra maestra de Gaudí y el máximo exponente de la arquitectura modernista catalana. Según datos de 2011, es el monumento más visitado de España, con 3,2 millones de visitantes, seguido por el Museo del Prado (2,9 millones) y la Alhambra de Granada (2,3).</p>
		<p>La construcción comenzó en estilo neogótico, pero, al asumir el proyecto Gaudí en 1883, se replanteó por completo. Según su proceder habitual, a partir de bocetos generales del edificio, improvisó la construcción a medida que avanzaba. Gaudí se hizo cargo del proyecto con sólo 31 años. Le dedicó el resto de su vida, los últimos quince en exclusiva.</p>
		<p>Una de sus ideas más innovadoras fue el diseño de las elevadas torres cónicas que sobresalen apuntadas sobre los portales, y que se van estrechando con la altura. Las proyectó con una torsión parabólica, que otorga una tendencia ascendente a toda la fachada, favorecida por multitud de ventanas que perforan la torre siguiendo formas espirales.</p>
		<p>El templo, cuando esté terminado, dispondrá de 18 torres: cuatro en cada una de las tres fachadas y, a modo de cúpulas, se dispondrá un sistema de seis torres, con la torre cimborio central —dedicada a Jesús— de 170 metros de altura, otras cuatro alrededor de esta, dedicadas a los evangelistas, y un segundo cimborio dedicado a la Virgen. Tanto el exterior como el interior están resueltos con un original sistema constructivo basado en la geometría reglada.</p>
		<p>En 1926, al morir Gaudí, solo se había construido una torre. Del proyecto del edificio solo se conservaban planos y un modelo en yeso que resultó muy dañado durante la Guerra Civil. Sin embargo, desde entonces han proseguido las obras sin interrupción: actualmente están terminados los portales del Nacimiento y de la Pasión, y se ha iniciado el de la Gloria; se ha cubierto todo el espacio interior, y se han puesto las bases de las seis torres centrales.</p>
		<p>La idea de construir un templo expiatorio dedicado a la Sagrada Familia en unos nuevos terrenos del Ensanche barcelonés fue del librero Josep Maria Bocabella, inspirado por el sacerdote Josep Manyanet —canonizado en 2004—, fundador de las congregaciones religiosas Congregación de Hijos de la Sagrada Familia y Congregación de Misioneras Hijas de la Sagrada Familia de Nazaret, encargadas de promover el culto a la Sagrada Familia y fomentar la educación cristiana de niños y jóvenes. Para tal fin, Bocabella fundó la Asociación de Devotos de San José, con el objetivo de recaudar fondos, y para la construcción del templo adquirió una manzana entera del Ensanche en un lugar conocido como El Poblet, cerca del Camp de l\'Arpa, en Sant Martí de Provençals, entre las calles Provença, Mallorca, Marina y Sardenya. El solar costó 172 000 pesetas de la época.</p>
		<p>Cuando Gaudí empezó a dirigir la construcción del templo, solo estaba construida la cripta, en la que modificó los capiteles, que pasaron de ser de estilo corintio a otro estilo inspirado en motivos vegetales. Gaudí evolucionó desde el primer proyecto neogótico hacia su estilo particular naturalista, orgánico, adaptado a la naturaleza. Una de sus fuentes de inspiración fue la Cueva del Salnitre en Collbató (provincia de Barcelona), así como la montaña de Montserrat. El arquitecto reusense opinaba que el gótico era imperfecto, porque sus formas rectas, su sistema de pilares y arbotantes, no reflejaba las leyes de la naturaleza, que según él es propensa a las formas geométricas regladas, como son el paraboloide hiperbólico, el hiperboloide, el helicoide y el conoide.</p>
		<p>Las superficies regladas son formas generadas por una recta, denominada generatriz, al desplazarse sobre una línea o varias, denominadas directrices. Gaudí las halló en abundancia en la naturaleza, como por ejemplo en juncos, cañas o huesos; decía que no existe mejor estructura que un tronco de árbol o un esqueleto humano. Estas formas son a la vez funcionales y estéticas, y Gaudí las empleó con gran sabiduría, sabiendo adaptar el lenguaje de la naturaleza a las formas estructurales de la arquitectura. El arquitecto asimilaba la forma helicoidal al movimiento, y la hiperboloidal a la luz.</p>
		<p>Gaudí fue modificando su concepción del templo a lo largo de los años, ya que las interrupciones de las obras por falta de recursos económicos le dieron tiempo para buscar nuevas soluciones estructurales. Asimismo, aprovechó su experimentación en otros proyectos para incorporar en la Sagrada Familia sus innovaciones más exitosas: la cripta de la Colonia Güell, así como las galerías y viaductos del Parque Güell, le sirvieron para adoptar nuevas soluciones arquitectónicas basadas en hiperboloides y paraboloides, así como en columnas helicoidales. Igualmente, las torres de la Sagrada Familia estaban inspiradas en un proyecto no realizado para unas Misiones Católicas Franciscanas en Tánger (1892), encargado por el marqués de Comillas.</p>
		<ul><li>En 2005 la parte construida por Gaudí en la Sagrada Familia (cripta y fachada del Nacimiento) fue declarada Patrimonio Cultural de la Humanidad por la Unesco. Es además, desde 2007, uno de los 12 Tesoros de España.</li><li>Ciertas estimaciones en función de los avances técnicos modernos y el creciente número de donaciones, prevén que su construcción podría finalizar en el año 2026, coincidiendo con la fecha del centenario del fallecimiento de Gaudí.</li><li>La Sagrada Familia es también conocida popularmente como La catedral de los pobres, a causa del cuadro homónimo del pintor modernista Joaquim Mir.</li><li>En la fachada de la Pasión, Subirachs añadió, al lado de El beso de Judas, un cuadrado mágico de 16 cifras que, sumando cuatro de ellas en cualquier sentido, siempre dan 33, la edad de Cristo al morir. Se pueden hacer 310 combinaciones distintas. Por otro lado, al sumar las dos únicas cifras que están repetidas (10 y 14) da 48, el mismo número que la palabra INRI al sumar la equivalencia de sus letras en números según el alfabeto latino (A=1, B=2, etc).</li></ul>
		<p>La Sagrada Familia abre al público entre las 9:00 y las 18:00 en invierno y entre las 9:00 y las 20:00 en verano. El acceso para visitantes se encuentra en la calle Cerdeña. Existen diversos tipos de entrada: simple, combinada con el Museo Gaudí del Parque Güell o con audioguía en diferentes idiomas. Los tickets para el ascensor se compran en el momento de ingresar al templo, es importante por tanto saber a cuál se subirá (Nacimiento o Pasión). Los tickets del ascensor funcionan con bandas horarias y la duración aproximada de la audioguía es de 90 minutos. En la Basílica de la Sagrada Familia se celebra una misa mensual en su nave central, y dos misas diarias en la cripta (una en catalán y otra en castellano).</p>
		<p><strong>Image:</strong> <a href="https://www.flickr.com/photos/7455207@N05/5471818259" rel="nofollow">Això és una meravella / This is a marvel</a> <cite>by SBA73</cite></p>'
);

$pages['parque_guell'] = array(
	'title' => 'Park Güell',
	'img' => '3',
	'content' => '<p>El Parque Güell es un reflejo de la plenitud artística de Gaudí: pertenece a su etapa naturalista, cuando lo que puso en práctica toda una serie de nuevas soluciones estructurales originadas en sus profundos análisis de la geometría reglada.</p>
		<p>A ello añade el artista catalán una gran libertad creativa y una imaginativa creación ornamental: partiendo de cierto barroquismo sus obras adquieren gran riqueza estructural, de formas y volúmenes desprovistos de rigidez racionalista o de cualquier premisa clásica. En el Parque Güell desplegó Gaudí todo su genio arquitectónico, y puso en práctica muchas de sus innovadoras soluciones estructurales que serían emblemáticas de su estilo organicista y que culminarían en la Sagrada Familia.</p>
		<p>El parque fue concebido por Güell y Gaudí como un conjunto estructurado donde, dentro de un incomparable marco de belleza natural, se situarían unas viviendas de alto standing, con todos los adelantos tecnológicos de la época para procurar el máximo confort, con unos acabados de gran calidad artística. Asimismo, idearon un conjunto impregnado de un fuerte simbolismo, ya que procuraron sintetizar en los elementos comunes del parque muchos de los ideales tanto políticos como religiosos que compartían mecenas y arquitecto: así, son perceptibles en el conjunto conceptos procedentes del catalanismo político —sobre todo en la escalinata de acceso, donde se representan los Países catalanes—, y de la religión católica —en el Monumento al Calvario, ideado en principio como capilla—. También es importante el elemento mitológico: según parece, Güell y Gaudí se inspiraron en el Templo de Apolo de Delfos para su concepción del parque.</p>
		<p>Por otro lado, numerosos expertos han querido ver en el parque una serie de referencias de variado signo, debido a la compleja iconografía aplicada por Gaudí al conjunto del proyecto urbanístico, referencias que van desde la reivindicación política hasta la exaltación religiosa, pasando por la mitología, la historia o la filosofía. En concreto, muchos estudiosos pretenden ver referencias a la masonería, hecho poco probable debido a las profundas creencias religiosas tanto de Gaudí como del conde Güell, y en todo caso no probado por ningún indicio objetivo en toda la historiografía del arquitecto modernista. La multiplicidad de símbolos desarrollada en el Parque Güell es, como se ha dicho, de signo político y religioso, en todo caso con cierto carácter mistérico debido al gusto de la época por los enigmas y acertijos.</p>
		<p>El parque tiene una extensión de 17,18 hectáreas (0,1718 km2). Se trata de un terreno devónico, formado por estratos de pizarra y caliza. En el diseño se pone claramente de manifiesto la mano de un arquitecto, y el estilo peculiar de Gaudí resulta evidente en cualquier elemento, por pequeño que sea. Existen formas onduladas, parecidas a los ríos de lava, y paseos cubiertos con columnas que tienen formas de árboles, estalactitas y formas geométricas. Muchas de las superficies están cubiertas con pedazos de cerámica o de vidrio a modo de mosaicos de colores, que recibe el nombre de trencadís. Por su localización al margen de la urbe y a una altitud elevada, este parque es un remanso de paz que contrasta con el ruido y frenesí de la capital catalana.</p>
		<p>Gaudí se empeñó en lograr una perfecta integración de sus obras en la naturaleza. Prueba de ello son las columnas constituidas de piedras de tamaños y formas muy variables, que sugieren troncos de árboles, estalactitas y cuevas naturales. Los ángulos rectos no aparecen en ningún lugar: las columnas están inclinadas como palmeras. Cuando Gaudí se hizo cargo del proyecto la zona estaba deforestada —como indicaba su nombre de Montaña Pelada—, por lo que mandó plantar nueva vegetación, escogiendo especies mediterráneas autóctonas, las que mejor se adaptaban al terreno: pino, algarrobo, encina, eucalipto, palmera, ciprés, higuera, almendro, ciruelo, mimosa, magnolia, pita, lentisco, hiedra, maquia, coscoja, retama, jara, romero, tomillo, lavanda, salvia, etc.</p>
		<p>Gaudí lo concibió con un sentido religioso a la vez que orgánico y urbanístico, ya que aprovechó el desnivel de 60 metros que tiene la montaña (cuya altura oscila de 150 a 210 metros) para proyectar un camino de elevación espiritual, y situando en su cima una capilla —que finalmente no se construyó—, en el lugar que actualmente ocupa el monumento al Calvario (o Colina de las Tres Cruces).</p>
		<p>Un proyecto paralelo al del Parque Güell y excelente muestra de jardín diseñado por Gaudí son los Jardines de Can Artigas, en La Pobla de Lillet (1905-1907), encargo del industrial textil Joan Artigas i Alart. Intervinieron en esta obra operarios que habían trabajado en el Parque Güell, realizando un proyecto parecido al del famoso parque barcelonés, por lo que las similitudes estilísticas y estructurales son evidentes entre ambas obras. Como en el Parque Güell, Gaudí diseñó unos jardines plenamente integrados en la naturaleza, con un conjunto de construcciones de líneas orgánicas que se integran perfectamente con el entorno natural.</p>
		<p>El punto central del parque lo constituye una inmensa plaza de forma oval, de 3.000 m2, construida entre 1907 y 1913. Su borde sirve de banco y ondula como una serpiente de 110 metros de longitud. Está recubierto de pequeñas piezas de cerámica y cristal obra de Josep Maria Jujol, con una de las técnicas preferidas del arquitecto, el trencadís. Según el plano original, la plaza central debía ser un teatro griego, apto para las reuniones comunitarias y para la celebración de eventos culturales y religiosos. En su parte exterior contiene un friso cubierto de gárgolas para desaguar la lluvia, así como pequeñas figuras en forma de gota de agua.</p>
		<p>El banco ondulante está formado por una sucesión de módulos cóncavos y convexos de 1,5 m, con un diseño ergonómico adaptado al cuerpo humano. La base es de trencadís blanco, y se corona con una decoración cerámica que recuerda los collages dadaístas o surrealistas, con motivos generalmente abstractos, pero también algún elemento figurativo, como los signos del Zodíaco, estrellas, flores, peces, cangrejos, etc. El trencadís se construyó con materiales de desecho, baldosas, botellas y trozos de vajilla. Predominan los colores azul, verde y amarillo, que para Gaudí simbolizaban la Fe, la Esperanza y la Caridad. Jujol incluyó también rosas y frases alegóricas en homenaje a la Virgen María, en catalán y en latín.</p>
		<p>Esta plaza está sin pavimentar, debido a que el agua que recoge procedente de precipitaciones es drenada y canalizada por las columnas que la sostienen, y es acumulada en un depósito subterráneo de 1.200 m3, para posteriormente ser empleada para regar el parque. Si el depósito sobrepasa un límite determinado, el agua sobrante es expulsada por el dragón que da la bienvenida al parque.</p>
		<p><strong>Image:</strong> <a href="http://commons.wikimedia.org/wiki/File:Parc_G%C3%BCell_27-2-12.jpg" rel="nofollow">Entrada al Parque Güell.</a> <cite>by Canaan</cite></p>'
);

$pages['casa_mila'] = array(
	'title' => 'Casa Milà',
	'img' => '4',
	'content' => '<p>La Casa Milà es un reflejo de la plenitud artística de Gaudí: pertenece a su etapa naturalista (primera década del siglo XX), periodo en que el arquitecto perfecciona su estilo personal, inspirándose en las formas orgánicas de la naturaleza, para lo que puso en práctica toda una serie de nuevas soluciones estructurales originadas en los profundos análisis efectuados por Gaudí de la geometría reglada. A ello añade el artista catalán una gran libertad creativa y una imaginativa creación ornamental: partiendo de cierto barroquismo sus obras adquieren gran riqueza estructural, de formas y volúmenes desprovistos de rigidez racionalista o de cualquier premisa clásica.</p>
		<p>La Casa Milà se encuentra en un chaflán del Paseo de Gracia con la calle Provenza, ocupado anteriormente por un chalet que hacía frontera entre los municipios de Barcelona y Gracia, antes de la anexión de esta villa a la ciudad condal en 1897. El chalet pertenecía a José Ferrer-Vidal y Soler, hermano de Luis Ferrer-Vidal y Soler, fundador de la Caixa de Pensions de Barcelona, y se formalizó la compra ante notario el 9 de junio de 1905. La zona se ubicaba en pleno Ensanche de Barcelona, proyectado por Ildefonso Cerdá y aprobado en 1859, con un sistema reticular de manzanas de viviendas con los ángulos recortados, con la previsión de edificar por dos lados y dedicar el resto a jardines, punto este último que finalmente no se llevó a cabo. Con el Ensanche, el Paseo de Gracia se convirtió en una de las principales arterias de la ciudad, por lo que fue elegido por la burguesía catalana para fijar sus residencias, gracias a lo cual esta vía creció rápidamente y se convirtió en un hervidero constructivo donde desarrollaron su labor los mejores arquitectos de Barcelona. Cabe resaltar que en el mismo Paseo de Gracia había construido Gaudí poco antes la Casa Batlló (1904-1906), y anteriormente había efectuado otras dos intervenciones hoy desaparecidas: la Farmacia Gibert (1879) y la decoración del bar Torino (1902).</p>
		<p>En ese contexto, Gaudí recibió el encargo de construir una casa señorial de parte de Pere Milà i Camps, un rico empresario cuyo padre, Pere Milà i Pi, había forjado su fortuna en la industria textil. Milà amplió el negocio familiar y diversificó los sectores donde probó fortuna, siendo por ejemplo el promotor de la plaza de toros La Monumental. También se dedicó a la política, y fue diputado por parte de Solidaritat Catalana. El señor Milà estaba casado con Roser Segimon i Artells, viuda de Josep Guardiola i Grau, un indiano enriquecido en América con plantaciones de café, cuya fortuna heredó su mujer. Así pues, la pareja gozaba de una privilegiada posición, hecho que quisieron plasmar en una casa de diseño innovador y gran lujo de detalles. Para ello compraron el solar del Paseo de Gracia en 1905, y encargaron el proyecto a Gaudí, entonces un arquitecto de gran renombre, que en aquella época trabajaba en diversos proyectos a la vez: el Templo Expiatorio de la Sagrada Familia (1883-1926), la Torre Bellesguard (1900-1909), el Parque Güell (1900-1914), la Casa Batlló (1904-1906) y la restauración de la Catedral de Santa María de Palma de Mallorca (1903-1914).</p>
		<p>El proyecto de Milà era construir un edificio de grandes dimensiones, destinar el piso principal para su propia residencia y el resto en régimen de alquiler, algo habitual en la época. Asimismo, la planta baja, en su parte exterior, fue destinada a tiendas, siendo la primera una sastrería abierta en 1928. El 2 de febrero de 1906 se presentaron los planos en el Ayuntamiento y se solicitó el permiso de obras. La construcción sufrió diversos retrasos, ya que el edificio superó en altura y anchura a lo establecido en las ordenanzas municipales, por lo que se impuso al señor Milà varias multas. Además, Gaudí abandonó la dirección de la obra en 1909 por divergencias con los Milà respecto a la decoración interior. La relación entre Gaudí y Milà se enfrió, y el arquitecto tuvo que llevar a juicio al promotor para cobrar sus honorarios (105 000 pesetas), que donó a los jesuitas. Para hacer frente al pago, el señor Milà tuvo que hipotecar la casa.</p>
		<p>El conjunto, por lo innovador, es una típica obra gaudiniana en la que las líneas geométricas son sólo rectas formando planos curvos. Toda su fachada está realizada en piedra calcárea, salvo la parte superior, que está cubierta de azulejos blancos, cuya combinación evoca una montaña nevada. En la azotea se encuentran grandes salidas de escalera rematadas con la cruz gaudiniana de cuatro brazos, y chimeneas recubiertas de fragmentos de cerámica, con la apariencia de cabezas de guerreros protegidas por yelmos. Cabe destacar la belleza del hierro forjado de sus balcones, que simulan plantas trepadoras, obra de los hermanos Lluís y Josep Badia i Miarnau.</p>
		<p>De formas orgánicas, la Casa Milà evoca sin lugar a dudas la naturaleza: diversos estudiosos han percibido en la Pedrera formas que recuerdan los riscos de Fra Guerau en la sierra de Prades cerca de Reus, el torrente de Pareis al norte de Mallorca o Sant Miquel del Fai en Bigues i Riells, todos ellos lugares visitados por Gaudí.</p>
		<p>La Casa Milà tiene tres fachadas, una en el Paseo de Gracia, otra en la calle Provenza, y otra que hace chaflán, siguiendo el esquema habitual del Ensanche proyectado por Cerdà. Sin embargo, las tres presentan una continuidad formal y estilística que, por su forma sinuosa y ondulada, parece una roca modelada por las olas del mar. El conjunto de entrantes y salientes imprime un dinamismo al conjunto que le otorga la sensación de estar en movimiento, a la vez que crea un juego de luces y sombras en constante cambio según la hora del día o la posición del espectador. Además de la forma ondulante de los muros de la fachada, la presencia de 33 balcones de hierro forjado, con una original forma similar a algas marinas, convierten el conjunto en una obra casi escultórica de gran tamaño. La mayoría de barandillas tiene una forma más bien abstracta, aunque se encuentran algunos detalles puntuales como una paloma, una máscara de teatro, una estrella de seis puntas, diversas flores y el escudo catalán.</p>
		<p>Las tres fachadas, de 30 metros de altura, contienen 150 ventanas, con diferentes soluciones estructurales, formas y tamaños, siendo más grandes las inferiores y más pequeñas las superiores, que reciben más luz. La piedra utilizada para su construcción tiene dos procedencias, una más dura, del Garraf, en la parte inferior; y otra menos dura, de Villafranca del Panadés, en la parte superior. Ambas dan un acabado en color blanco crema, que genera diversas tonalidades según la luz incidente, y están acabadas con una textura rugosa, que proporciona un aspecto orgánico.</p>
		<p>Fachada del Paseo de Gracia: orientada al sudoeste, tiene 21,15 metros de largo y 630 m2 de superficie, con nueve balcones que dan a la calle. Está coronada con la palabra Ave del Ave María, con una decoración en relieve de lirios, símbolo de la pureza de la Virgen. Es la única que no tiene puerta de acceso. La parte perteneciente a esta fachada de la planta baja estaba destinada a carbonera, y originalmente tenía rejas, que fueron retiradas cuando se transformó en tiendas comerciales.</p>
		<p>Fachada del chaflán: tiene 20,10 metros de largo, y al ser la central es la más conocida del edificio. Alberga una de las dos puertas de acceso, flanqueada por dos grandes columnas (habitualmente apodadas «patas de elefante») que sostienen la tribuna del piso principal, el del matrimonio Milà. Al parecer, para el conjunto de puerta y tribuna Gaudí se inspiró en la obra de un arquitecto barroco madrileño, Pedro de Ribera. El techo de la tribuna tiene una claraboya para proporcionarle luz, bajo la que se sitúa una concha esculpida. En la parte superior de la fachada se encuentra una rosa en relieve, y la inicial M de María, que habrían sido la base de la escultura de María y los arcángeles que finalmente no se colocó. En los dos laterales del chaflán se encuentran en la parte superior las palabras Gratia y Plena del Ave María.</p>
		<p>Fachada de la calle Provenza: tiene 43,35 metros de largo, por lo que es la más extensa, y cuenta con una puerta de acceso al edificio. Orientada al sureste, recibe luz prácticamente todo el día, por lo que Gaudí la diseñó con más ondulaciones que en las otras dos fachadas, así como unos balcones más sobresalientes, para crear más sombra. En la parte superior se sitúan las palabras Dominus y Tecum del Ave María.</p>
		<p>Junto a estas fachadas hay que mencionar la fachada posterior, que da al patio interno de la manzana formada por el Paseo de Gracia y las calles Provenza, Rosellón y Pau Claris, no visible para el público en general, ya que sólo tienen acceso los vecinos. Tiene 25 metros de largo, con una superficie de 800 m2. Más sobria que la fachada principal, presenta sin embargo la misma forma ondulatoria, con un desfase entre los distintos pisos que forman entrantes y salientes, emulando el oleaje marino, con unas grandes terrazas con barandillas de hierro de ligero diseño en forma de rombos, que permiten el paso de la luz. Esta fachada está elaborada con un rebozado de cemento y cal estucados de color marrón rojizo.</p>
		<p><strong>Image:</strong> <a href="https://www.flickr.com/photos/10352740@N03/8802740680/" rel="nofollow">Barcelona Chimeneas y Patio </a> <cite>by Turol Jones</cite></p>'
);

$pages['gaudi'] = array(
	'title' => 'Gaudí',
	'img' => '5',
	'content' => '<p>Gaudí fue un arquitecto con un sentido innato de la geometría y el volumen, así como una gran capacidad imaginativa que le permitía proyectar mentalmente la mayoría de sus obras antes de pasarlas a planos. De hecho, pocas veces realizaba planos detallados de sus obras; prefería recrearlos sobre maquetas tridimensionales, moldeando todos los detalles según los iba ideando mentalmente. En otras ocasiones, iba improvisando sobre la marcha, dando instrucciones a sus colaboradores sobre lo que debían hacer.</p>
		<p>Dotado de una fuerte intuición y capacidad creativa, Gaudí concebía sus edificios de una forma global atendiendo, tanto a las soluciones estructurales, como las funcionales y decorativas. Estudiaba hasta el más mínimo detalle de sus creaciones, integrando en la arquitectura toda una serie de trabajos artesanales que dominaba él mismo a la perfección: cerámica, vidriería, forja de hierro, carpintería, etc. Asimismo, introdujo nuevas técnicas en el tratamiento de los materiales, como su famoso “trencadís” hecho con piezas de cerámica de desecho.</p>
		<p>Después de unos inicios influenciado por el arte neogótico, así como ciertas tendencias orientalizantes, Gaudí desembocó en el modernismo en su época de mayor efervescencia, entre finales del siglo XIX y principios del XX. Sin embargo, el arquitecto reusense fue más allá del modernismo ortodoxo, creando un estilo personal basado en la observación de la naturaleza, fruto del cual fue su utilización de formas geométricas regladas, como el paraboloide hiperbólico, el hiperboloide, el helicoide y el conoide.</p>
		<p>La arquitectura de Gaudí está marcada por un fuerte sello personal, caracterizado por la búsqueda de nuevas soluciones estructurales, que logró después de toda una vida dedicada al análisis de la estructura óptima del edificio, integrado en su entorno y siendo una síntesis de todas las artes y oficios. Mediante el estudio y la práctica de nuevas y originales soluciones, la obra de Gaudí culminará en un estilo orgánico, inspirado en la naturaleza, pero sin perder la experiencia aportada por estilos anteriores, generando una obra arquitectónica que es una simbiosis perfecta de la tradición y la innovación. Asimismo, toda su obra está marcada por las que fueron sus cuatro grandes pasiones en la vida: la arquitectura, la naturaleza, la religión y el amor a Cataluña.</p>
		<p>La obra de Gaudí ha alcanzado con el transcurso del tiempo una amplia difusión internacional, siendo innumerables los estudios dedicados a su forma de entender la arquitectura. Hoy día es admirado tanto por profesionales como por el público en general: la Sagrada Familia es actualmente uno de los monumentos más visitados de España. Entre 1984 y 2005 siete de sus obras han sido consideradas Patrimonio de la Humanidad por la Unesco.</p>
		<p><strong>Image:</strong> <a href="https://www.flickr.com/photos/69214385@N04/13258594634" rel="nofollow">Dawn Mosaic</a> <cite>by Don McCullough</cite></p>'
);
$pages['more'] = array(
	'title' => 'More Works',
	'img' => '6',
	'content' => '
		<p>La obra de Gaudí es de difícil clasificación. Inscrito en el modernismo, pertenece sin duda a esta corriente por su afán de renovación –sin romper por ello con la tradición–, la búsqueda de la modernidad, el sentido ornamental aplicado a su obra y el carácter multidisciplinar otorgado a sus realizaciones, donde tienen un papel fundamental los trabajos artesanales. A estas premisas Gaudí añade ciertas dosis de barroquismo, la inclusión de los adelantos tecnológicos y el mantenimiento de lenguajes arquitectónicos tradicionales, que junto a la inspiración en la naturaleza y el toque de originalidad que otorga a sus realizaciones constituyen la amalgama que proporciona al conjunto de su obra un sello personal y único en la historia de la arquitectura.</p>
		<p>Cronológicamente, es difícil establecer unas pautas que determinen de forma veraz la evolución de su estilo. Si bien parte de unos postulados claramente historicistas para enmarcarse de lleno en el modernismo que surgía con fuerza en el último tercio del siglo XIX en Cataluña y llegar por fin a la resolución final de su estilo personal y orgánico, esta evolución no presenta unas etapas precisas con rupturas entre unas y otras, sino que en todas hay reflejos de las primeras, a medida que las va asimilando y superando. Una de las mejores periodificaciones realizadas de la obra de Gaudí es la de su discípulo y biógrafo Joan Bergós, efectuada según criterios plásticos y estructurales; Bergós establece cinco periodos en la producción gaudiniana: periodo preliminar, mudéjar-morisco, gótico evolucionado, naturalismo expresionista y síntesis orgánica.</p>
		<h2>Primeras obras</h2>
		<p>Sus primeras realizaciones, tanto durante su etapa de estudiante como las primeras ejecutadas al obtener el título, destacan por la gran precisión de los detalles, la utilización de la geometría superior y la preponderancia de las consideraciones mecánicas en el cálculo de estructuras.</p></p>
		<<h2>Etapa orientalista</h2>
		<p>En estos años Gaudí realiza una serie de obras de marcado gusto oriental, inspiradas en el arte del Próximo y Lejano Oriente (India, Persia, Japón), así como en el arte islámico hispánico, principalmente el mudéjar y nazarí. Gaudí emplea con gran profusión la decoración en azulejo cerámico, así como los arcos mitrales, cartelas de ladrillo visto y remates en forma de templete o cúpula.</p>
		<p>Entre 1883 y 1888 construyó la Casa Vicens, encargo del corredor de bolsa Manuel Vicens i Montaner. Está estructurada en cuatro niveles o plantas, con tres fachadas y un amplio jardín, con una fuente monumental de ladrillo formada por un arco parabólico encima del cual había un paso entre columnas. La casa se cerraba con un muro de cerca con un reja de hierro colado, decorada con hojas de palmito, obra de Llorenç Matamala. Los muros de la casa son de mampostería alternada con filas de azulejo, que reproduce unas flores amarillas propias de la zona; la casa se remata con chimeneas y unas torres en forma de templetes. En el interior destacan los techos de vigas de madera policromada, adornados con temas florales de "papier maché"; los muros tienen esgrafiados de motivos vegetales, así como pinturas obra de Josep Torrescasana; por último, el suelo es de mosaico romano de "opus tesselatum". Una de las estancias más originales es el fumadero, donde destaca el techo en forma de cielo raso decorado con mucarnas árabes, que recuerdan el Generalife de la Alhambra de Granada.</p>
		<h2>Período neogótico</h2>
		<p>En esta etapa Gaudí se inspiró sobre todo en el arte gótico medieval, el cual asume de forma libre, personal, intentando mejorar sus soluciones estructurales. El neogótico fue en aquella época uno de los estilos historicistas de mayor éxito, sobre todo a raíz de los estudios teóricos de Viollet-le-Duc. Gaudí estudió con profundidad el gótico catalán, balear y rosellonés, así como el leonés y el castellano en sus estancias en León y Burgos, llegando al convencimiento de que era un estilo imperfecto, a medio resolver. En sus obras elimina la necesidad de contrafuertes mediante el empleo de superficies regladas, y suprime cresterías y calados excesivos.</p>
		<h2>Etapa naturalista</h2>
		<p>En este periodo Gaudí perfecciona su estilo personal, inspirándose en las formas orgánicas de la naturaleza, poniendo en práctica toda una serie de nuevas soluciones estructurales originadas en los profundos análisis efectuados por Gaudí de la geometría reglada. A ello añade el arquitecto una gran libertad creativa y una imaginativa creación ornamental. Partiendo de cierto barroquismo sus obras adquieren gran riqueza estructural, de formas y volúmenes desprovistos de rigidez racionalista o de cualquier premisa clásica.</p>
		<p>Por encargo de la razón social Hijos de Pedro Mártir Calvet, Gaudí construyó la Casa Calvet (1898-1899), en la calle Caspe de Barcelona. La fachada es de piedra de sillería de Montjuïc, adornada con balcones de hierro forjado y rematada por dos frontones, coronados con cruces de hierro de forja. Destaca asimismo en la fachada la tribuna del piso principal, decorada con motivos vegetales y mitológicos. En este proyecto Gaudí utilizó un cierto estilo barroco, visible en el uso de columnas salomónicas, la decoración con temas florales y el proyecto de azotea con cascada y maceteros de aire rococó. Por esta obra ganó en 1900 el premio al mejor edificio del año otorgado por el Ayuntamiento de Barcelona.</p>
		<h2>Etapa final: culminación de su estilo</h2>
		<p>En los últimos años de su carrera, dedicados casi en exclusiva a la Sagrada Familia, Gaudí llega a la culminación de su estilo naturalista, haciendo una síntesis de todas las soluciones y estilos probados hasta aquel entonces. Gaudí logra una perfecta armonía en la interrelación entre los elementos estructurales y los ornamentales, entre plástica y estética, entre función y forma, entre contenido y continente, logrando la integración de todas las artes en un todo estructurado y lógico.</p>
		<p><strong>Image:</strong> <a href="http://commons.wikimedia.org/wiki/File:Parc_G%C3%BCell,_plaf%C3%B3_de_trencad%C3%ADs.jpg" rel="nofollow">Parc Güell, plafó de trencadís</a> <cite>by Enfo</cite></p>
		<!--<ul>
			<li><strong>Image:</strong> <a href="" rel="nofollow"></a> <cite>by </cite></li>
			<li><strong>Image:</strong> <a href="https://www.flickr.com/photos/juantiagues/7654827278" rel="nofollow">Astorga-Figuras en el Palacio de Gaudí</a> <cite>by juantiagues</cite></li>
			<li><strong>Image:</strong> <a href="" rel="nofollow"></a> <cite>by </cite></li>
			<li><strong>Image:</strong> <a href="" rel="nofollow"></a> <cite>by </cite></li>
		</ul>-->
		'
);
?>
